from math import pi

SIMULATION_SPEED = 0.01 # seconds
CULL_PERIOD = 300
VISUALISE = True

ENV_WIDTH = 1000
ENV_HEIGHT = 1000
ENV_N_FOOD = 200
ENV_N_ANIMALS = 100

ANIMAL_FULLNESS = 300

MUTATION_RATE = 0.05

CLONE_NUM = 5

FOOD_SATIATION = 70
FOOD_RADIUS = 2
FOOD_STRENGTH = 1
FOOD_EAT_DISTANCE = FOOD_RADIUS
FOOD_COLOR = "yellow"

GROWTH_RATE = 5 / FOOD_SATIATION

ANIMAL_HEAD_RADIUS  = 5
ANIMAL_HEAD_COLOR   = "red"
ANIMAL_BODY_LENGTH  = 15
ANIMAL_BODY_COLOR   = "black"

THE_BRAIN = [1,3,2]

THRESHOLD_OUTPUT = 0.75

ANIMAL_MOVE_SPEED = 1
ANIMAL_MOVE_ANGLE = pi / 8

NUM_CHILDREN = 1
