from math import pi

SIMULATION_SPEED = 0.01 # seconds
CULL_PERIOD = 300
VISUALISE = True

ENV_WIDTH = 500
ENV_HEIGHT = 500
ENV_N_ANIMALS = 5

FOOD_GEN_RATE = 0.8

ANIMAL_FULLNESS = 80
FOOD_SATIATION = 60
STOMACH_SIZE = 300

MUTATION_RATE = 0.05

CLONE_NUM = 5

FOOD_RADIUS = 5
FOOD_COLOR = "yellow"

ANIMAL_HEAD_RADIUS  = 5
ANIMAL_HEAD_COLOR   = "red"
ANIMAL_BODY_LENGTH  = 15
ANIMAL_BODY_COLOR   = "black"

THE_BRAIN = [1,1]

THRESHOLD_OUTPUT = 0.75

ANIMAL_MOVE_SPEED = 2
ANIMAL_MOVE_ANGLE = pi / 8

NUM_CHILDREN = 1

FOOD_STRENGTH = 1
FOOD_EAT_DISTANCE = FOOD_RADIUS
