from math import pi

ENV_WIDTH = 1000
ENV_HEIGHT = 1000

ENV_MAX_DISTANCE_SQ = ENV_WIDTH ** 2 + ENV_HEIGHT ** 2

VISUALISE = True

ENV_MAX_ORGANISMS = 40

ORGANISM_BRAIN = [1,4,2,2]
ORGANISM_HEADSIZE = 5
ORGANISM_TAILSIZE = 16

ORGANISM_TURN_AMOUNT = pi / 8
ORGANISM_SPEED = 2

PHOTOSYNTHESIS_RATE = 0.01
ORGANISM_INITIAL_SIZE = 100
ORGANISM_SIZE_LOSS = 0.001
ORGANISM_SIZE_EFFICIENCY = 0.997

MUTATION_RATE = 0.2

EAT_DISTANCE_SQ = 25

SLOW_DOWN = 0#.005
